apiVersion: traefik.containo.us/v1alpha1
kind: TraefikService
metadata:
  name: argo-combined-app-service
  namespace: argo-combined-app
  labels:
    app: argo-combined-app
spec:
  weighted:
    services:
      - name: argo-combined-app # k8s service name that you need to create for stable application version
        port: 80
      - name: argo-combined-app-canary # k8s service name that you need to create for new application version
        port: 80

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argo-combined-app
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`argo-combined-app.local`) || Host(`argo-combined-app.prod-00.openticket.tech`)
      services:
        - name: argo-combined-app
